#!/bin/bash
set -e

# POSTGRES_USER == ckan_prod
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE postgres SUPERUSER LOGIN PASSWORD '$CKAN_POSTGRES_PASSWORD';
    CREATE ROLE datastore_ro NOSUPERUSER NOCREATEDB NOCREATEROLE LOGIN PASSWORD '$DATASTORE_POSTGRES_READONLY_PASSWORD';
    CREATE DATABASE datastore_prod OWNER ckan_prod ENCODING 'utf-8';
    GRANT ALL PRIVILEGES ON DATABASE datastore_prod TO ckan_prod;
EOSQL
